name: Notebook tests

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
  pull_request: {}

jobs:

  run-template:
    name: Template
    uses: ./.github/workflows/reusable-execute-notebook.yml
    with:
      runs-on: "ubuntu-latest"
      arch: amd64
      out-name: "template"
      notebook: "template.ipynb"
    secrets: inherit

  run-compile-crc:
    name: Compile crc
    uses: ./.github/workflows/reusable-execute-notebook.yml
    with:
      runs-on: "ubuntu-latest"
      arch: amd64
      out-name: "crc"
      notebook: "projects/crc.ipynb"
    secrets: inherit
